version: "3.7"

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=video
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DOCKER=1
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/site

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - api
